# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'survey-list-app' do
  supports_swift_versions '>= 3.0', '< 4.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for survey-list-app
  pod 'Alamofire', '~> 4'

  target 'survey-list-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
