# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'survey-list-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for survey-list-app

  target 'survey-list-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
